export const communitySections = [
    {
        key: 'hero',
        title: 'Hero Section',
        description: 'Top campaign headline and CTA.',
        contentTitle: 'Together We Grow',
        heading: '$0.50 FROM EVERY PURCHASE YOU MAKE SUPPORTS GARMENT\'S WORKERS\' CHILDREN',
        sectionDescription: 'Every purchase makes a difference. We donate $0.50 from every order to support workers\' children in our community — helping create brighter futures through care, education, and opportunity.',
        buttonText: 'Let\'s Make a Purchase',
        buttonUrl: '/products',
        status: 'active',
    },
    {
        key: 'features',
        title: 'Impact Features',
        description: 'Education, care, and opportunity cards.',
        featureImage: '/uploads/heroes/images/hero1.webp',
        featureItems: [
            {
                id: 'education',
                icon: 'graduation-cap',
                title: 'Education',
                description: 'School supplies, tuition assistance, and scholarships that keep kids in the classroom.',
            },
            {
                id: 'care',
                icon: 'heart-handshake',
                title: 'Care',
                description: 'Healthcare, nutrition, and safe spaces for the children of the people who make our garments.',
            },
            {
                id: 'opportunity',
                icon: 'sprout',
                title: 'Opportunity',
                description: 'Mentorship and skills programs that open doors to brighter, self-made futures.',
            },
        ],
        buttonText: 'Learn More',
        buttonUrl: '/about',
        status: 'active',
    },
    {
        key: 'community-center',
        title: 'Community Center',
        description: 'Programs and support initiatives section.',
        contentTitle: 'Community Center',
        heading: 'A SPACE BUILT FOR THE PEOPLE WHO MAKE US.',
        communityImage: '/uploads/about/giving-back/1781586266_about_giving_back_6a30d95a8dd5c4.14738819.webp',
        communityItems: [
            {
                id: 'learning-hub',
                icon: 'book-open',
                title: 'Learning Hub',
                description: 'Workshops, library access, and skill-building sessions led by community members.',
            },
            {
                id: 'health-wellness',
                icon: 'heart-pulse',
                title: 'Health & Wellness',
                description: 'Regular health check-ups, awareness sessions, and on-call counseling support.',
            },
            {
                id: 'social-support',
                icon: 'users',
                title: 'Social Support',
                description: 'Community events, peer groups, and family engagement programs.',
            },
            {
                id: 'recreation',
                icon: 'sparkles',
                title: 'Recreation',
                description: 'Spaces for relaxation, cultural activities, and team-building moments.',
            },
        ],
        buttonText: 'Explore Programs',
        buttonUrl: '/community',
        status: 'active',
    },
    {
        key: 'gallery',
        title: 'Community Gallery',
        description: 'Moments from the community photo showcase.',
        galleryItems: [
            {
                id: 'community-1',
                src: '/uploads/about/giving-back/1781586266_about_giving_back_6a30d95a8dd5c4.14738819.webp',
                alt: 'Children participating in a classroom activity.',
                label: 'Community',
                date: '2026-06-18',
            },
            {
                id: 'community-2',
                src: '/uploads/about/story/1781528584_about_story_6a2ff8086e82f3.63671374.webp',
                alt: 'Students listening during a learning session.',
                label: 'Learning Session',
                date: '2026-06-12',
            },
            {
                id: 'community-3',
                src: '/uploads/about/hero/1781527310_about_hero_6a2ff30ec4c0d8.12870098.jpg',
                alt: 'Community program moment with children.',
                label: 'Community Program',
                date: '2026-06-10',
            },
            {
                id: 'community-4',
                src: '/uploads/about/mission/1781585355_about_mission_6a30d5cb0eab87.68288187.jpg',
                alt: 'Mentorship and care initiative.',
                label: 'Mentorship',
                date: '2026-06-07',
            },
            {
                id: 'community-5',
                src: '/uploads/our-story/images/1781584475_story_image_6a30d25bc69ac5.59079252.webp',
                alt: 'Shared community space and daily activities.',
                label: 'Shared Space',
                date: '2026-06-04',
            },
            {
                id: 'community-6',
                src: '/uploads/heroes/images/1780912831_image.webp',
                alt: 'A support event for garment workers families.',
                label: 'Support Event',
                date: '2026-06-01',
            },
        ],
        buttonText: 'View Gallery',
        buttonUrl: '#gallery',
        status: 'active',
    },
    {
        key: 'newsletter',
        title: 'Newsletter',
        description: 'Email signup section at the end of page.',
        buttonText: 'Subscribe',
        buttonUrl: '#newsletter',
        status: 'active',
    },
];
