export const sustainabilitySections = [
    {
        key: 'hero',
        title: 'Hero Section',
        description: 'Top sustainability heading and subtitle.',
        contentTitle: '',
        heading: '',
        sectionDescription: '',
        featureImage: '',
        featureImage2: '',
        ourMaterialsItems: [],
        buttonText: '',
        buttonUrl: '',
        status: 'active',
    },

    {
        key: 'longevity',
        title: 'Designed for Longevity',
        description: 'Sustainability daily-practice story section.',
        contentTitle: 'Sustainability, Practiced Daily',
        heading: 'Designed for Longevity',
        sectionDescription: '',
        featureImage: '',
        featureImage2: '',
        ourMaterialsItems: [],
        buttonText: '',
        buttonUrl: '',
        status: 'active',
    },
    {
        key: 'mindful-materials',
        title: 'Thoughtfully Chosen Materials',
        description: 'Mindful materials and composition highlights.',
        contentTitle: 'Mindful Materials',
        heading: 'Thoughtfully Chosen Materials',
        sectionDescription: '',
        featureImage: '',
        featureImage2: '',
        ourMaterialsItems: [],
        buttonText: '',
        buttonUrl: '',
        status: 'active',
    },
   
    {
        key: 'behind-the-craft',
        title: 'Behind the Craft',
        description: 'Craft process and people-first production section.',
        contentTitle: 'Fabric & Technology',
        heading: 'Behind the Craft',
        sectionDescription: '',
        featureImage: '',
        featureImage2: '',
        ourMaterialsItems: [],
        buttonText: '',
        buttonUrl: '',
        status: 'active',
    },
    {
        key: 'fabric-innovations',
        title: 'Our Materials',
        description: 'Material innovation and performance story section.',
        contentTitle: 'Material Innovation',
        heading: 'Our Materials',
        sectionDescription: '',
        featureImage: '',
        featureImage2: '',
        ourMaterialsItems: [],
        buttonText: '',
        buttonUrl: '',
        status: 'active',
    },
];
